config/routes.rb
Rails.application.routes.draw do
  
  resources :ingredients
  resources :recipes
  resources :clients
  resources :users

  resources :clients, only: [:show] do
    resources :restrictions, only: [:show, :index, :new, :create]
  end

  get '/recipes/search' => 'recipes#search'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  root 'welcome#home'
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :client_restrictions
    has_many :restrictions, through: :client_restrictions

    validates :name, presence: true 
    validates :name, uniqueness: true

    def restrictions_attributes=(restrictions_attributes)
        restrictions_attributes.map do |attr|
            attr.each do |res|
                self.restrictions << Restriction.find_or_create_by(name: res["name"].downcase) unless res["name"].blank?
            end 
        end 
    end 

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
    before_action :require_login
    
    def show 
        @client = Client.find(params[:id])
    end 

    def index
        @clients = Client.order(:name)
    end

    def new
        @client = Client.new
        5.times { @client.restrictions.build }
    end

    def create
        @client = Client.new(client_params)
        if @client.save
            redirect_to @client
        else 
            render :new 
        end
    end 

    def edit
        @client = Client.find(params[:id])
        5.times { @client.restrictions.build }
    end

    def update
        @client = Client.find(params[:id])
        @client.restrictions.delete_all
        if @client.update(client_params)
            redirect_to client_path(@client)
        else
            render :edit
        end
    end 

    def destroy
        @client = Client.find(params[:id])
        @client.destroy
        redirect_to clients_path
      end
      
    private
        def client_params
            params.require(:client).permit(:name, :user_id,
                restrictions_attributes: [
                    :name,
                    :id
                ]
            )
        end

        def require_login
            return head(:forbidden) unless session.include? :user_id
        end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>

    <% if @client.errors.any? %>
        <% @client.errors.full_messages.each do |msg| %>
            <%= msg %>
        <% end %>
    <% end %>

    <p><%= f.label :name, "Client Name: "%>
    <%= f.text_field :name %></p>

    <%= f.fields_for :restrictions do |r|  %>
       
       <br><%= r.label :name, "Restriction: " %>
       
       <%= r.collection_select(:name, Restriction.all, :name, :name, :include_blank => true) %>

    <% end %>

    <%= f.fields_for :restrictions do |r|  %>
       
        <br><%= r.label :name, "Restriction: " %>
         <%= r.text_field :name %>
         
     <% end %>

    <p><%= f.submit %></p>
<% end %>

app/views/clients/edit.html.erb
<h2>Edit <%= @client.name %></h2>

<%= render 'form' %>

<p><%= button_to "Delete #{@client.name}", client_path, :method => "delete", data: {confirm: "Are you sure you want to permanently delete #{@client.name}?"} %></p>

<p><%= button_to "Homepage", root_path, :method => "get" %></p>

app/views/clients/index.html.erb
<h1>View All Your Clients</h1>

<section class="todoapp">
	<section class="main" style="display: block;">
		<ul class="todo-list">

            <% @clients.each do |client| %>
                <ul>
                <%= link_to client.name, "clients/#{client.id}" %>
                </ul>
            <% end %>

        </ul>
	</section>
</section>

<p><%= button_to "Add another client", new_client_path, :method => "get" %></p>

<p><%= button_to "Homepage", root_path, :method => "get" %></p>

app/views/clients/new.html.erb
<h1>Create a New Client</h1>

<%= render 'form' %>

<p><%= button_to "Homepage", root_path, :method => "get" %></p>

app/views/clients/show.html.erb
<h3><%= @client.name %></h3>

<section class="todoapp">
<p><%= @client.name %>'s <label>restrictions: </label></p>
	<section class="main" style="display: block;">
		<ul class="todo-list">

            <% @client.restrictions.each do |attr| %>
            <p><%= link_to attr.name, client_restriction_path(@client, attr) %></p>
            <% end %>

        </ul>
	</section>
</section>

<p><%= button_to "Edit #{@client.name}", edit_client_path, :method => "get" %></p>

<p><%= button_to "New Restriction", new_client_restriction_path(@client), :method => "get" %></p>

<p><%= button_to "Add another client", new_client_path, :method => "get" %></p>

<p><%= button_to "View All Your Clients", clients_path, :method => "get" %></p>

<p><%= button_to "Homepage", root_path, :method => "get" %></p>