config/routes.rb
Rails.application.routes.draw do
  
  resources :ingredients
  resources :recipes
  resources :clients
  resources :users

  resources :clients, only: [:show] do
    resources :restrictions, only: [:show, :index, :new, :create]
  end

  get '/recipes/search' => 'recipes#search'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  root 'welcome#home'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    before_action :require_logged_in
  
    def home
    end
end

app/views/welcome/home.html.erb
<h1>Hi, <%= @user.name %></h1>

<section class="todoapp">

	<section class="main" style="display: block;">
		<ul class="todo-list">
            <li data-id="1564063687532" class="">
                <div class="view">
                    <label><%= link_to "Create a Client", new_client_path %></label>
                </div>
                <div class="view">
                    <label><%= link_to "View All Your Clients", clients_path %></label>
                </div>
                <div class="view">
                    <label><%= link_to "Create a Recipe", new_recipe_path %></label>
                </div>
                <div class="view">
                    <label><%= link_to "View All Your Recipes", recipes_path %></label>
                </div>
            </li>
        </ul>
	</section>

</section>

<p><%= button_to "Logout", logout_path, :method => "delete" %></p>